name: check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install tools
        run: pacman -Syu --noconfirm --needed git make shellcheck

      - name: Get the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check the scripts
        run: make check
